create table if not exists public.project_config (
  project_id text primary key,
  name text not null,
  description text,
  tone text,
  restrictions text,
  provider text default 'gemini',
  model text default 'gemini-2.5-flash',
  api_key text,
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  role text not null,
  content text not null,
  project text not null,
  timestamp timestamptz not null default timezone('utc'::text, now()),
  embedding jsonb,
  metadata jsonb
);

create index if not exists idx_messages_project_timestamp
on public.messages (project, timestamp);

create table if not exists public.conversation_summaries (
  project text primary key,
  summary text not null,
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.low_confidence_queries (
  id bigint generated by default as identity primary key,
  project text not null,
  query text not null,
  score double precision not null,
  timestamp timestamptz not null default timezone('utc'::text, now())
);
